# Generated by Django 6.0.4 on 2026-05-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo de procedimentos')),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField(verbose_name='Data Inspeção')),
                ('vazamento_detectado', models.BooleanField(verbose_name='Vazamento Detectado')),
                ('area_vazamento', models.CharField(verbose_name='Localização do Vazamento')),
                ('vazamento', models.CharField(verbose_name='Local do vazamento')),
                ('observacao', models.TextField(verbose_name='Observações')),
                ('procedimentos', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laudo.procedimentos', verbose_name='Procedimento de Localização')),
            ],
        ),
    ]
