# Generated by Django 6.0.4 on 2026-05-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('laudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='crm.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
