# Generated by Django 6.0.4 on 2026-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0002_laudo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='procedimentos',
        ),
        migrations.AddField(
            model_name='laudo',
            name='procedimentos',
            field=models.ManyToManyField(to='laudo.procedimentos', verbose_name='Procedimento de Localização'),
        ),
    ]
